[package]
name = "kiss2d"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.11"
bresenham = "0.1"
rusttype = "0.7"
image = { version = "0.20", default-features = false }
